version: "3.8"

services:
  # MySQL数据库
  mysql:
    image: mysql
    container_name: mall_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mq123
      MYSQL_DATABASE: mall_db
      # MYSQL_USER: mall_user
      # MYSQL_PASSWORD: mall123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mall_network

  # Redis缓存
  # redis:
  #   image: redis:7-alpine
  #   container_name: mall_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - mall_network

  # 商城API服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mall_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Mq123
      - DB_NAME=mall_db
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mysql
      # - redis
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    networks:
      - mall_network

  # Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: mall_nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  #     - ./public:/var/www/html
  #   depends_on:
  #     - api
  #   networks:
  #     - mall_network

volumes:
  mysql_data:
  # redis_data:

networks:
  mall_network:
    driver: bridge
